export const pizzaFeatures = new Map([
  ["light", "на тонком тесте"],
  ["large", "на толстом тесте"],
  ["small", "23 см"],
  ["normal", "32 см"],
  ["big", "45 см"],
  ["tomato", "томатный"],
  ["creamy", "сливочный"],
  ["mushrooms", "грибы"],
  ["cheddar", "чеддер"],
  ["salami", "салями"],
  ["ham", "ветчина"],
  ["ananas", "ананас"],
  ["bacon", "бекон"],
  ["onion", "лук"],
  ["chile", "чили"],
  ["jalapeno", "халапеньо"],
  ["olives", "маслины"],
  ["tomatoes", "томаты"],
  ["salmon", "лосось"],
  ["mozzarella", "моцарелла"],
  ["parmesan", "пармезан"],
  ["blue_cheese", "блю чиз"],
]);
